/**
 * Per-agent setup recipes for the Agents modal. Keep this file the single
 * source of truth for how to connect an AI assistant to Scoutpost —
 * the UI is a dumb renderer over it.
 *
 * Each agent has one or two connection paths:
 *   - 'cli'  — the agent shells out to the `scout` binary. No MCP server to
 *              run; the agent inspects commands as plain shell. Preferred
 *              for shell-capable agents (Claude Code, Codex, Cursor,
 *              Windsurf, Gemini CLI, Goose, Hermes).
 *   - 'mcp'  — the agent connects to the remote MCP server at MCP_URL.
 *              The only option for chat UIs without shell access. The
 *              "Claude Cowork" entry covers Claude Desktop, claude.ai,
 *              and Cowork — they all use the same Anthropic-cloud-brokered
 *              custom-connector flow, with a single "Add custom connector"
 *              + Connect step kicking off DCR + OAuth automatically.
 *              ChatGPT custom MCP connectors are gated to Business /
 *              Enterprise / Edu workspaces, so we don't list a recipe;
 *              direct ChatGPT users at the browser-based "paste scout CLI
 *              export" workflow generated by `lib/setup/setup-generator.ts`.
 *
 * `defaultPath` per agent picks the one we lead with; the modal exposes
 * a toggle when both are available.
 */

import type { AgentSlug } from "./agent-icons";
import { type AgentTargetContext, HOSTED_AGENT_TARGET } from "./agent-targets";

export type InstallPath = "cli" | "mcp";

export type RecipeMode =
  | "cli-command"
  | "cli-install"
  | "config-file"
  | "ui-steps"
  | "generic";

export type RecipeSetupKind = "automated-cli" | "manual";

export interface RecipeWarning {
  title: string;
  body: string;
}

export interface Recipe {
  /** Short headline that renders under the path selector. */
  tagline: string;

  /** Whether the modal should show an agent-facing setup prompt or manual steps. */
  setupKind: RecipeSetupKind;

  /** Optional tier / compatibility callout (stdio bridge, beta status, etc.). */
  warning?: RecipeWarning;

  mode: RecipeMode;

  /** Single shell command for `cli-command` mode. Templated with {{MCP_URL}}. */
  command?: string;

  /** Install one-liner for `cli-install` mode (curl + chmod). */
  installCommand?: string;
  /** Config commands shown as a second copy-able block for `cli-install` mode. */
  configCommands?: string[];

  /** File path for `config-file` mode (e.g. ~/.cursor/mcp.json). */
  configPath?: string;
  /** JSON / TOML / YAML / URL snippet for `config-file`, `ui-steps`, `generic` modes. Templated with {{MCP_URL}}. */
  configSnippet?: string;
  /** Language hint for syntax highlighting (json, toml, yaml). */
  configLang?: "json" | "toml" | "yaml";

  /** Numbered steps for `ui-steps` mode (also appended to `cli-command` mode). */
  uiSteps?: string[];

  /** Optional video walkthrough for manual UI setup flows. */
  video?: {
    src: string;
    title: string;
  };

  /** Docs link shown next to the setup block. */
  docsUrl?: string;
  docsLabel?: string;

  /** Optional: verify prompt (overrides the default "List my Scoutpost scouts"). */
  verifyPrompt?: string;
  /** Optional explicit verification steps for manual setup flows. */
  verifySteps?: string[];
}

export const CLI_README_URL =
  "https://github.com/buriedsignals/cojournalist-os/blob/main/cli/README.md";
const CLI_DENO_INSTALL_URL =
  "https://raw.githubusercontent.com/buriedsignals/cojournalist-os/master/cli/scout.ts";
export const MCP_URL = HOSTED_AGENT_TARGET.mcpUrl;
export const SKILL_URL = HOSTED_AGENT_TARGET.skillUrl;

function fill(tpl: string, target: AgentTargetContext): string {
  return tpl
    .replace(/\{\{MCP_URL\}\}/g, target.mcpUrl)
    .replace(/\{\{API_BASE_URL\}\}/g, target.apiBaseUrl)
    .replace(/\{\{APP_URL\}\}/g, target.appUrl)
    .replace(/\{\{SKILL_URL\}\}/g, target.skillUrl)
    .replace(
      /\{\{SUPABASE_ANON_KEY\}\}/g,
      target.supabaseAnonKey ?? "<SUPABASE_ANON_KEY>",
    );
}

// ----- Shared CLI recipe ----------------------------------------------------
// All shell-capable agents use the same install + config steps. The only
// per-agent variation is where skill.md is persisted (see SKILL_PROMPTS).

const CLI_INSTALL_DEFAULT =
  `deno install -A -g -n scout ${CLI_DENO_INSTALL_URL}`;

const CLI_CONFIG_COMMANDS = [
  "scout config set api_url={{API_BASE_URL}}",
  "{{SUPABASE_ANON_KEY_COMMAND}}",
  "scout config set api_key=<paste cj_... key from the API panel>",
];

const sharedCliRecipe: Recipe = {
  tagline:
    "Install the scout CLI — your agent shells out to it. No MCP server to manage, commands stay visible in the transcript.",
  setupKind: "automated-cli",
  mode: "cli-install",
  installCommand: CLI_INSTALL_DEFAULT,
  configCommands: CLI_CONFIG_COMMANDS,
  docsUrl: CLI_README_URL,
  docsLabel: "CLI install + other platforms",
  verifyPrompt: "Run `scout scouts list` and tell me what I’m monitoring.",
};

// ----- Per-agent MCP recipes (the original table) ---------------------------

const mcpRecipes: Partial<Record<AgentSlug, Recipe>> = {
  "claude-code": {
    tagline: "One command in your terminal. OAuth opens on first use.",
    setupKind: "manual",
    mode: "cli-command",
    command: "claude mcp add --transport http scoutpost {{MCP_URL}}",
    uiSteps: [
      "Run the command above in your terminal.",
      "Claude Code opens your default browser to sign in. If no browser opens, run `claude mcp list` to print the auth URL and open it manually.",
      "Approve the connection — the CLI completes the OAuth handshake automatically.",
    ],
    docsUrl: "https://code.claude.com/docs/en/mcp",
    docsLabel: "Claude Code MCP docs",
  },

  "claude-cowork": {
    tagline:
      "Add a custom connector in Claude — same flow for Claude Desktop, claude.ai, and Cowork. No terminal needed.",
    setupKind: "manual",
    mode: "ui-steps",
    uiSteps: [
      "Open Claude Desktop, claude.ai, or Cowork and go to Customize → Connectors. On Team or Enterprise plans, an Owner must first add the connector in Organization settings → Connectors.",
      'Click "+" → "Add custom connector". On Team or Enterprise, choose Custom → Web.',
      "Paste the URL below as the Remote MCP Server URL, then click Add.",
      'Click Connect on the new entry — not Configure. (If the card defaults to Configure, click "..." → Remove, then re-add. The first probe drives the OAuth flow.)',
      "A Scoutpost sign-in opens. Anthropic brokers remote connector traffic from its cloud, even for Desktop and Cowork. Approve the OAuth request.",
      'Enable the connector in a conversation from the "+" menu → Connectors before asking Claude to list your scouts.',
    ],
    video: {
      src: "/videos/claude-cowork-connect.mp4",
      title: "Claude Cowork connector walkthrough",
    },
    configSnippet: MCP_URL,
    docsUrl:
      "https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp",
    docsLabel: "Claude custom connector docs",
    verifySteps: [
      "Open a conversation where the Scoutpost connector is enabled.",
      'Ask: "List my Scoutpost scouts."',
      "If the connector is missing, remove and re-add it from Connectors, then connect again.",
    ],
  },

  "codex-mcp": {
    tagline:
      "Add Scoutpost as a Streamable HTTP MCP server in Codex, then run the OAuth login command.",
    setupKind: "manual",
    mode: "config-file",
    configPath: "~/.codex/config.toml",
    configLang: "toml",
    configSnippet: `[mcp_servers.scoutpost]
url = "{{MCP_URL}}"`,
    docsUrl: "https://developers.openai.com/codex/mcp",
    docsLabel: "Codex MCP docs",
    verifySteps: [
      "Save the config block above in ~/.codex/config.toml or a trusted project .codex/config.toml.",
      "Run `codex mcp login scoutpost` and approve the OAuth flow.",
      "Run `/mcp` in the Codex TUI and confirm scoutpost is connected.",
    ],
  },

  cursor: {
    tagline: "Add an entry to Cursor’s MCP config. OAuth on first use.",
    setupKind: "manual",
    mode: "config-file",
    configPath: "~/.cursor/mcp.json",
    configLang: "json",
    configSnippet: `{
  "mcpServers": {
    "scoutpost": {
      "url": "{{MCP_URL}}"
    }
  }
}`,
    docsUrl: "https://cursor.com/docs/mcp",
    docsLabel: "Cursor MCP docs",
    verifySteps: [
      "Save this globally at ~/.cursor/mcp.json or per project at .cursor/mcp.json.",
      "Run `agent mcp login scoutpost` if Cursor asks for OAuth.",
      "Run `agent mcp list` or open Cursor Settings → Features → Model Context Protocol and confirm scoutpost is connected.",
    ],
  },

  windsurf: {
    tagline: "Add via Windsurf’s MCP panel, or edit the config file.",
    setupKind: "manual",
    mode: "config-file",
    configPath: "~/.codeium/windsurf/mcp_config.json",
    configLang: "json",
    configSnippet: `{
  "mcpServers": {
    "scoutpost": {
      "serverUrl": "{{MCP_URL}}"
    }
  }
}`,
    docsUrl: "https://docs.windsurf.com/windsurf/cascade/mcp",
    docsLabel: "Windsurf MCP docs",
    verifySteps: [
      "Save this in ~/.codeium/windsurf/mcp_config.json or add it through Windsurf Settings → Cascade → MCP Servers.",
      "Press the refresh button in the MCP Servers panel after adding the server.",
      "Open the scoutpost MCP settings page and confirm tools are enabled.",
    ],
  },

  "gemini-cli": {
    tagline: "Use Gemini CLI’s MCP manager to add a Streamable HTTP server.",
    setupKind: "manual",
    mode: "cli-command",
    command: "gemini mcp add --transport http scoutpost {{MCP_URL}}",
    uiSteps: [
      "Run the command above in your terminal. It writes to your Gemini CLI MCP settings.",
      'If you prefer manual config, add `"httpUrl": "{{MCP_URL}}"` under `mcpServers.scoutpost` in ~/.gemini/settings.json.',
      "Use `/mcp` or `gemini mcp list` to inspect connection status and diagnostics.",
    ],
    configSnippet: "{{MCP_URL}}",
    docsUrl:
      "https://github.com/google-gemini/gemini-cli/blob/main/docs/tools/mcp-server.md",
    docsLabel: "Gemini CLI MCP docs",
    verifySteps: [
      "Run `gemini mcp list`.",
      "Start Gemini CLI and run `/mcp` if the server does not appear connected.",
      'Ask: "List my Scoutpost scouts."',
    ],
  },

  goose: {
    tagline: "Configure via the Goose CLI prompt flow.",
    setupKind: "manual",
    mode: "cli-command",
    command: "goose configure",
    uiSteps: [
      "Run `goose configure` in your terminal.",
      'Choose "Add Extension" → "Streamable HTTP".',
      "Name the extension `scoutpost`.",
      "Paste the URL below when prompted.",
      "Authorize in the browser window that opens.",
    ],
    configSnippet: MCP_URL,
    docsUrl: "https://block.github.io/goose/docs/mcp/",
    docsLabel: "Goose MCP docs",
    verifySteps: [
      "Restart Goose or reload extensions after the browser authorization finishes.",
      'Ask: "List my Scoutpost scouts."',
    ],
  },

  openclaw: {
    tagline:
      "Experimental: save Scoutpost in OpenClaw’s MCP registry for runtimes that consume it.",
    setupKind: "manual",
    warning: {
      title: "Experimental registry path",
      body:
        "OpenClaw’s documented MCP command stores outbound server definitions and does not prove the target server is reachable immediately. Use this only if your OpenClaw runtime consumes saved MCP registry entries.",
    },
    mode: "cli-command",
    command:
      `openclaw mcp set scoutpost '{"url":"{{MCP_URL}}","transport":"streamable-http"}'`,
    configLang: "json",
    configSnippet: `{
  "mcp": {
    "servers": {
      "scoutpost": {
        "url": "{{MCP_URL}}",
        "transport": "streamable-http"
      }
    }
  }
}`,
    docsUrl: "https://docs.openclaw.ai/cli/mcp",
    docsLabel: "OpenClaw MCP docs",
    verifySteps: [
      "Run `openclaw mcp show scoutpost --json` to confirm the registry entry.",
      "Verify in the specific OpenClaw runtime profile that consumes MCP registry entries; the registry command alone does not connect to the server.",
    ],
  },

  hermes: {
    tagline: "Add a server block to Hermes’ YAML config.",
    setupKind: "manual",
    mode: "config-file",
    configPath: "~/.hermes/config.yaml",
    configLang: "yaml",
    configSnippet: `mcp_servers:
  scoutpost:
    url: {{MCP_URL}}
    auth: oauth`,
    docsUrl:
      "https://hermes-agent.nousresearch.com/docs/reference/mcp-config-reference",
    docsLabel: "Hermes Agent MCP docs",
    verifySteps: [
      "Save the YAML block in ~/.hermes/config.yaml.",
      "Run `/reload-mcp` in Hermes, or restart Hermes.",
      "Approve the OAuth browser flow on first connect.",
    ],
  },

  other: {
    tagline: "Any MCP-speaking client. Paste this URL and authorize.",
    setupKind: "manual",
    mode: "generic",
    configSnippet: MCP_URL,
    docsUrl: "https://modelcontextprotocol.io",
    docsLabel: "Model Context Protocol docs",
  },
};

// ----- Which path is primary per agent --------------------------------------
// Rule of thumb: if the agent has shell access, default to CLI. Chat UIs
// without shell (Claude Cowork) are MCP-only. "Other" offers both.

const CLI_CAPABLE: AgentSlug[] = [
  "claude-code",
  "codex-cli",
  "cursor",
  "windsurf",
  "gemini-cli",
  "goose",
  "hermes",
];

const CLI_ONLY: AgentSlug[] = ["codex-cli"];
const MCP_ONLY: AgentSlug[] = ["claude-cowork", "codex-mcp"];

export interface AgentRecipes {
  /** Which paths are available for this agent, in display order. */
  paths: InstallPath[];
  /** The path we recommend (preselected in the UI). */
  default: InstallPath;
  /** Recipe per available path, values filled in. */
  recipes: Partial<Record<InstallPath, Recipe>>;
}

/** Resolve recipes + default path for an agent. */
export function getAgentRecipes(
  slug: AgentSlug,
  target: AgentTargetContext = HOSTED_AGENT_TARGET,
): AgentRecipes {
  const hasCli = CLI_CAPABLE.includes(slug);
  const hasMcp = !CLI_ONLY.includes(slug) && Boolean(mcpRecipes[slug]);
  // "Other" gets both CLI + MCP so generic users can pick.
  const includeCli = (hasCli || slug === "other") && !MCP_ONLY.includes(slug);

  const paths: InstallPath[] = [];
  const recipes: Partial<Record<InstallPath, Recipe>> = {};

  if (includeCli) {
    paths.push("cli");
    recipes.cli = fillRecipe(sharedCliRecipe, target);
  }
  if (hasMcp) {
    paths.push("mcp");
    recipes.mcp = fillRecipe(mcpRecipes[slug]!, target);
  }

  const defaultPath: InstallPath = includeCli && !MCP_ONLY.includes(slug)
    ? "cli"
    : "mcp";
  return { paths, default: defaultPath, recipes };
}

function fillRecipe(r: Recipe, target: AgentTargetContext): Recipe {
  const configCommands = r.configCommands
    ?.map((command) =>
      command === "{{SUPABASE_ANON_KEY_COMMAND}}"
        ? target.deploymentKind === "supabase"
          ? `scout config set supabase_anon_key=${
            target.supabaseAnonKey || "<SUPABASE_ANON_KEY>"
          }`
          : null
        : fill(command, target)
    )
    .filter((command): command is string => Boolean(command));

  return {
    ...r,
    command: r.command ? fill(r.command, target) : undefined,
    configCommands,
    configSnippet: r.configSnippet ? fill(r.configSnippet, target) : undefined,
  };
}

/**
 * Legacy single-recipe accessor. Returns the recipe for the agent’s default
 * path. Kept for any consumer that hasn’t yet switched to getAgentRecipes.
 */
export function getRecipe(
  slug: AgentSlug,
  target: AgentTargetContext = HOSTED_AGENT_TARGET,
): Recipe {
  const { default: defaultPath, recipes } = getAgentRecipes(slug, target);
  return recipes[defaultPath] ??
    fillRecipe(mcpRecipes[slug] ?? sharedCliRecipe, target);
}

/**
 * Per-agent skill-save location. Tells the agent where skill.md should be
 * persisted so it auto-loads in future sessions. The skill file itself
 * (SKILL_URL) is agnostic — same content for every agent.
 */
const SKILL_LOCATIONS: Record<AgentSlug, string> = {
  "claude-code": ".claude/skills/scoutpost.md",
  "claude-cowork": "this Project's instructions (or your memory)",
  "codex-cli": "AGENTS.md (or ~/.codex/AGENTS.md for global reuse)",
  "codex-mcp": "AGENTS.md (or ~/.codex/AGENTS.md for global reuse)",
  cursor: ".cursor/rules/scoutpost.mdc",
  windsurf: ".windsurf/rules/scoutpost.md",
  "gemini-cli": "GEMINI.md (or ~/.gemini/GEMINI.md for global reuse)",
  goose: ".goosehints (or ~/.config/goose/.goosehints for global reuse)",
  openclaw:
    "somewhere your agent loads on startup (project rules, system prompt, or memory)",
  hermes: "~/.hermes/skills/scoutpost.md",
  other:
    "somewhere your agent loads on startup (project rules, system prompt, or memory)",
};

const CLI_INSTALL_LINE = `deno install -A -g -n scout ${CLI_DENO_INSTALL_URL}`;

/**
 * Build a complete 1-click setup prompt that walks the agent (and user)
 * through connecting to Scoutpost end-to-end. The agent:
 *
 *   1. Fetches skill.md so it understands the product
 *   2. Installs the scout CLI (or configures MCP)
 *   3. Prompts the user for the API key and calls the right config command
 *   4. Verifies the connection
 *   5. Reports back what it can do and where it saved skill.md
 *
 * Paste this into any agent's first message and it self-configures.
 */
export function getSetupPrompt(
  slug: AgentSlug,
  path: InstallPath = "cli",
  target: AgentTargetContext = HOSTED_AGENT_TARGET,
): string {
  const location = SKILL_LOCATIONS[slug] ?? SKILL_LOCATIONS.other;
  const selfHostedNote = target.deploymentKind === "supabase"
    ? ` This is a self-hosted newsroom deployment; use only ${target.appUrl}, ${target.apiBaseUrl}, and ${target.mcpUrl}. Do not connect to scoutpost.ai.`
    : "";

  if (path === "mcp") {
    return [
      `Set me up with Scoutpost.${selfHostedNote} Do this in order, narrating each step:`,
      ``,
      `1. Fetch ${target.skillUrl} and save it to ${location} so it auto-loads in future sessions. This is the product skill — it tells you how to drive Scoutpost.`,
      `2. Configure the remote MCP server at ${target.mcpUrl}. If a config file edit is needed, show me the exact file path and diff before saving.`,
      `3. The MCP server uses OAuth — when the connector prompts me to sign in, I'll approve it in the browser. Do not ask me for a JWT or API key; the OAuth flow handles auth.`,
      `4. Verify the connection by listing my scouts. If the tool isn't available yet, tell me to reload the chat.`,
      `5. Summarise what Scoutpost lets you do for me and suggest one concrete thing you'd use it for based on my current work.`,
    ].join("\n");
  }

  return [
    `Set me up with Scoutpost via the scout CLI.${selfHostedNote} Do this in order, narrating each step:`,
    ``,
    `1. Fetch ${target.skillUrl} and save it to ${location} so it auto-loads in future sessions. This is the product skill — it tells you how to drive Scoutpost.`,
    `2. Install the scout CLI by running: ${CLI_INSTALL_LINE}`,
    `   (Requires Deno 2.x. If Deno is missing, install it first from https://deno.com/.)`,
    `3. Tell me to generate an API key at ${target.apiKeyCreateUrl} → Agents → API → Create key (it's shown once). Do NOT ask me to paste the key into this chat — credentials in a transcript leak into logs and screenshots. Instead, have me run these commands in my own terminal so the key never enters the conversation:`,
    `     scout config set api_url=${target.apiBaseUrl}`,
    ...(target.deploymentKind === "supabase"
      ? [
        `     scout config set supabase_anon_key=${
          target.supabaseAnonKey || "<SUPABASE_ANON_KEY>"
        }`,
      ]
      : []),
    `     scout config set api_key=cj_...   # I replace cj_... with the real key locally`,
    `4. After I confirm I've done that, verify by running: scout --version && scout scouts list — if it returns my scouts, we're connected. The CLI reads the key from ~/.scoutpost/config.json, so you never see it.`,
    `5. From now on, use the scout CLI to create scouts, list findings, and verify units on my behalf. Don't ask me to open the web UI when you can do it via the CLI.`,
    `6. Summarise what Scoutpost lets you do for me and suggest one concrete thing you'd use it for based on my current work.`,
  ].join("\n");
}

/** Backwards-compatible alias. */
export function getSkillPrompt(
  slug: AgentSlug,
  path: InstallPath = "cli",
  target: AgentTargetContext = HOSTED_AGENT_TARGET,
): string {
  return getSetupPrompt(slug, path, target);
}

/** @deprecated Use getSetupPrompt(agent, path) — kept for backwards compatibility. */
export const SKILL_PROMPT = getSetupPrompt("other", "cli");
