/**
 * Per-agent setup recipes for the Agents modal. Keep this file the single
 * source of truth for how to connect an AI assistant to coJournalist —
 * the UI is a dumb renderer over it.
 *
 * Each agent has one or two connection paths:
 *   - 'cli'  — the agent shells out to the `cojo` binary. No MCP server to
 *              run; the agent inspects commands as plain shell. Preferred
 *              for shell-capable agents (Claude Code, Codex, Cursor,
 *              Windsurf, Gemini CLI, Goose, Hermes).
 *   - 'mcp'  — the agent connects to the remote MCP server at MCP_URL.
 *              The only option for chat UIs without shell access. The
 *              "Claude Cowork" entry covers Claude Desktop, claude.ai,
 *              and Cowork — they all use the same Anthropic-cloud-brokered
 *              custom-connector flow, with a single "Add custom connector"
 *              + Connect step kicking off DCR + OAuth automatically.
 *              ChatGPT custom MCP connectors are gated to Business /
 *              Enterprise / Edu workspaces, so we don't list a recipe;
 *              direct ChatGPT users at the browser-based "paste cojo CLI
 *              export" workflow generated by `lib/setup/setup-generator.ts`.
 *
 * `defaultPath` per agent picks the one we lead with; the modal exposes
 * a toggle when both are available.
 */

import type { AgentSlug } from "./agent-icons";
import { HOSTED_AGENT_TARGET, type AgentTargetContext } from "./agent-targets";

export type InstallPath = "cli" | "mcp";

export type RecipeMode =
  | "cli-command"
  | "cli-install"
  | "config-file"
  | "ui-steps"
  | "generic";

export interface RecipeWarning {
  title: string;
  body: string;
}

export interface Recipe {
  /** Short headline that renders under the path selector. */
  tagline: string;

  /** Optional tier / compatibility callout (stdio bridge, beta status, etc.). */
  warning?: RecipeWarning;

  mode: RecipeMode;

  /** Single shell command for `cli-command` mode. Templated with {{MCP_URL}}. */
  command?: string;

  /** Install one-liner for `cli-install` mode (curl + chmod). */
  installCommand?: string;
  /** Config commands shown as a second copy-able block for `cli-install` mode. */
  configCommands?: string[];

  /** File path for `config-file` mode (e.g. ~/.cursor/mcp.json). */
  configPath?: string;
  /** JSON / TOML / YAML / URL snippet for `config-file`, `ui-steps`, `generic` modes. Templated with {{MCP_URL}}. */
  configSnippet?: string;
  /** Language hint for syntax highlighting (json, toml, yaml). */
  configLang?: "json" | "toml" | "yaml";

  /** Numbered steps for `ui-steps` mode (also appended to `cli-command` mode). */
  uiSteps?: string[];

  /** Docs link shown next to the setup block. */
  docsUrl?: string;
  docsLabel?: string;

  /** Optional: verify prompt (overrides the default "List my coJournalist scouts"). */
  verifyPrompt?: string;
}

export const CLI_README_URL =
  "https://github.com/buriedsignals/cojournalist-os/blob/main/cli/README.md";
const CLI_DENO_INSTALL_URL =
  "https://raw.githubusercontent.com/buriedsignals/cojournalist-os/master/cli/cojo.ts";
export const MCP_URL = HOSTED_AGENT_TARGET.mcpUrl;
export const SKILL_URL = HOSTED_AGENT_TARGET.skillUrl;

function fill(tpl: string, target: AgentTargetContext): string {
  return tpl
    .replace(/\{\{MCP_URL\}\}/g, target.mcpUrl)
    .replace(/\{\{API_BASE_URL\}\}/g, target.apiBaseUrl)
    .replace(/\{\{APP_URL\}\}/g, target.appUrl)
    .replace(/\{\{SKILL_URL\}\}/g, target.skillUrl)
    .replace(/\{\{SUPABASE_ANON_KEY\}\}/g, target.supabaseAnonKey ?? "<SUPABASE_ANON_KEY>");
}

// ----- Shared CLI recipe ----------------------------------------------------
// All shell-capable agents use the same install + config steps. The only
// per-agent variation is where skill.md is persisted (see SKILL_PROMPTS).

const CLI_INSTALL_DEFAULT =
  `deno install -A -g -n cojo ${CLI_DENO_INSTALL_URL}`;

const CLI_CONFIG_COMMANDS = [
  "cojo config set api_url={{API_BASE_URL}}",
  "{{SUPABASE_ANON_KEY_COMMAND}}",
  "cojo config set api_key=<paste cj_... key from the API panel>",
  "cojo --version && cojo scouts list",
];

const sharedCliRecipe: Recipe = {
  tagline:
    "Install the cojo CLI — your agent shells out to it. No MCP server to manage, commands stay visible in the transcript.",
  mode: "cli-install",
  installCommand: CLI_INSTALL_DEFAULT,
  configCommands: CLI_CONFIG_COMMANDS,
  docsUrl: CLI_README_URL,
  docsLabel: "CLI install + other platforms",
  verifyPrompt: "Run `cojo scouts list` and tell me what I’m monitoring.",
};

// ----- Per-agent MCP recipes (the original table) ---------------------------

const mcpRecipes: Record<AgentSlug, Recipe> = {
  "claude-code": {
    tagline: "One command in your terminal. OAuth opens on first use.",
    mode: "cli-command",
    command: "claude mcp add --transport http cojournalist {{MCP_URL}}",
    uiSteps: [
      "Run the command above in your terminal.",
      "Claude Code opens your default browser to sign in. If no browser opens, run `claude mcp list` to print the auth URL and open it manually.",
      "Approve the connection — the CLI completes the OAuth handshake automatically.",
    ],
    docsUrl: "https://code.claude.com/docs/en/mcp",
    docsLabel: "Claude Code MCP docs",
  },

  "claude-cowork": {
    tagline:
      "Add a custom connector in Claude — same flow for Claude Desktop, claude.ai, and Cowork. No terminal needed.",
    mode: "ui-steps",
    uiSteps: [
      "Open Claude Desktop, claude.ai, or Cowork (Settings → Connectors).",
      'Click "+" → "Add custom connector".',
      "Paste the URL below as the Remote MCP Server URL and click Add.",
      'Click Connect on the new entry — not Configure. (If the card defaults to Configure, click "..." → Remove, then re-add. The first probe drives the OAuth flow.)',
      "A coJournalist sign-in opens (Anthropic brokers OAuth from their cloud — no separate desktop browser pops up). Approve, and the connector card flips to connected with the tools listed.",
    ],
    configSnippet: MCP_URL,
    docsUrl:
      "https://support.claude.com/en/articles/11175166-get-started-with-custom-connectors-using-remote-mcp",
    docsLabel: "Claude custom connector docs",
  },

  codex: {
    tagline:
      "Codex Desktop speaks Streamable HTTP natively with OAuth. Paste the URL — no terminal needed.",
    mode: "ui-steps",
    uiSteps: [
      "Open Codex Desktop → Settings → MCP Servers → Connect to a custom MCP.",
      'Switch to the "Streamable HTTP" tab (the dialog defaults to STDIO — that\'s the wrong one for remote servers).',
      "Name: cojournalist. URL: paste the value below. Leave Authorization blank — Codex runs the OAuth handshake on first use. Save.",
      "Approve the coJournalist sign-in in the browser tab Codex opens. The connector flips to connected and tools appear in the Sources/Tools panel.",
      "Terminal alternative (codex-cli): add `[mcp_servers.cojournalist]` with `url = \"{{MCP_URL}}\"` to ~/.codex/config.toml, then run `codex mcp login cojournalist`. Older codex-cli builds may need `experimental_use_rmcp_client = true` in the same file.",
    ],
    configSnippet: "{{MCP_URL}}",
    docsUrl: "https://developers.openai.com/codex/mcp",
    docsLabel: "Codex MCP docs",
  },

  cursor: {
    tagline: "Add an entry to Cursor’s MCP config. OAuth on first use.",
    mode: "config-file",
    configPath: "~/.cursor/mcp.json",
    configLang: "json",
    configSnippet: `{
  "mcpServers": {
    "cojournalist": {
      "url": "{{MCP_URL}}"
    }
  }
}`,
    docsUrl: "https://cursor.com/docs/mcp",
    docsLabel: "Cursor MCP docs",
  },

  windsurf: {
    tagline: "Add via Windsurf’s MCP panel, or edit the config file.",
    mode: "config-file",
    configPath: "~/.codeium/windsurf/mcp_config.json",
    configLang: "json",
    configSnippet: `{
  "mcpServers": {
    "cojournalist": {
      "serverUrl": "{{MCP_URL}}"
    }
  }
}`,
    docsUrl: "https://docs.windsurf.com/windsurf/cascade/mcp",
    docsLabel: "Windsurf MCP docs",
  },

  "gemini-cli": {
    tagline: "Add a block to Gemini CLI’s settings file.",
    mode: "config-file",
    configPath: "~/.gemini/settings.json",
    configLang: "json",
    configSnippet: `{
  "mcpServers": {
    "cojournalist": {
      "httpUrl": "{{MCP_URL}}"
    }
  }
}`,
    docsUrl: "https://geminicli.com/docs/tools/mcp-server/",
    docsLabel: "Gemini CLI MCP docs",
  },

  goose: {
    tagline: "Configure via the Goose CLI prompt flow.",
    mode: "cli-command",
    command: "goose configure",
    uiSteps: [
      "Run `goose configure` in your terminal.",
      'Choose "Add Extension" → "Streamable HTTP".',
      "Name the extension `cojournalist`.",
      "Paste the URL below when prompted.",
      "Authorize in the browser window that opens.",
    ],
    configSnippet: MCP_URL,
    docsUrl: "https://block.github.io/goose/docs/mcp/",
    docsLabel: "Goose MCP docs",
  },

  openclaw: {
    tagline: "OpenClaw’s MCP client is in active beta.",
    warning: {
      title: "Beta support",
      body:
        "Native MCP client support for OpenClaw is tracked upstream (openclaw/openclaw#29053). Until that lands in the stable release, follow the upstream install guide below and paste the URL into the MCP extensions panel.",
    },
    mode: "generic",
    configSnippet: MCP_URL,
    docsUrl: "https://github.com/openclaw/openclaw/issues/29053",
    docsLabel: "OpenClaw MCP tracking issue",
  },

  hermes: {
    tagline: "Add a server block to Hermes’ YAML config.",
    mode: "config-file",
    configPath: "~/.hermes/config.yaml",
    configLang: "yaml",
    configSnippet: `mcp_servers:
  cojournalist:
    url: {{MCP_URL}}
    transport: streamable_http`,
    docsUrl:
      "https://hermes-agent.nousresearch.com/docs/user-guide/features/mcp",
    docsLabel: "Hermes Agent MCP docs",
  },

  other: {
    tagline: "Any MCP-speaking client. Paste this URL and authorize.",
    mode: "generic",
    configSnippet: MCP_URL,
    docsUrl: "https://modelcontextprotocol.io",
    docsLabel: "Model Context Protocol docs",
  },
};

// ----- Which path is primary per agent --------------------------------------
// Rule of thumb: if the agent has shell access, default to CLI. Chat UIs
// without shell (Claude Cowork, OpenClaw) are MCP-only. "Other" offers both.

const CLI_CAPABLE: AgentSlug[] = [
  "claude-code",
  "codex",
  "cursor",
  "windsurf",
  "gemini-cli",
  "goose",
  "hermes",
];

const MCP_ONLY: AgentSlug[] = ["claude-cowork", "openclaw"];

export interface AgentRecipes {
  /** Which paths are available for this agent, in display order. */
  paths: InstallPath[];
  /** The path we recommend (preselected in the UI). */
  default: InstallPath;
  /** Recipe per available path, values filled in. */
  recipes: Partial<Record<InstallPath, Recipe>>;
}

/** Resolve recipes + default path for an agent. */
export function getAgentRecipes(slug: AgentSlug, target: AgentTargetContext = HOSTED_AGENT_TARGET): AgentRecipes {
  const hasCli = CLI_CAPABLE.includes(slug);
  const hasMcp = !MCP_ONLY.includes(slug) ? true : true; // every agent has some MCP recipe
  // "Other" gets both CLI + MCP so generic users can pick.
  const includeCli = hasCli || slug === "other";

  const paths: InstallPath[] = [];
  const recipes: Partial<Record<InstallPath, Recipe>> = {};

  if (includeCli) {
    paths.push("cli");
    recipes.cli = fillRecipe(sharedCliRecipe, target);
  }
  paths.push("mcp");
  recipes.mcp = fillRecipe(mcpRecipes[slug], target);

  const defaultPath: InstallPath = includeCli && !MCP_ONLY.includes(slug)
    ? "cli"
    : "mcp";
  return { paths, default: defaultPath, recipes };
}

function fillRecipe(r: Recipe, target: AgentTargetContext): Recipe {
  const configCommands = r.configCommands
    ?.map((command) =>
      command === "{{SUPABASE_ANON_KEY_COMMAND}}"
        ? target.deploymentKind === "supabase"
          ? `cojo config set supabase_anon_key=${target.supabaseAnonKey || "<SUPABASE_ANON_KEY>"}`
          : null
        : fill(command, target),
    )
    .filter((command): command is string => Boolean(command));

  return {
    ...r,
    command: r.command ? fill(r.command, target) : undefined,
    configCommands,
    configSnippet: r.configSnippet ? fill(r.configSnippet, target) : undefined,
  };
}

/**
 * Legacy single-recipe accessor. Returns the recipe for the agent’s default
 * path. Kept for any consumer that hasn’t yet switched to getAgentRecipes.
 */
export function getRecipe(slug: AgentSlug, target: AgentTargetContext = HOSTED_AGENT_TARGET): Recipe {
  const { default: defaultPath, recipes } = getAgentRecipes(slug, target);
  return recipes[defaultPath] ?? mcpRecipes[slug];
}

/**
 * Per-agent skill-save location. Tells the agent where skill.md should be
 * persisted so it auto-loads in future sessions. The skill file itself
 * (SKILL_URL) is agnostic — same content for every agent.
 */
const SKILL_LOCATIONS: Record<AgentSlug, string> = {
  "claude-code": ".claude/skills/cojournalist.md",
  "claude-cowork": "this Project's instructions (or your memory)",
  codex: "AGENTS.md (or ~/.codex/AGENTS.md for global reuse)",
  cursor: ".cursor/rules/cojournalist.mdc",
  windsurf: ".windsurf/rules/cojournalist.md",
  "gemini-cli": "GEMINI.md (or ~/.gemini/GEMINI.md for global reuse)",
  goose: ".goosehints (or ~/.config/goose/.goosehints for global reuse)",
  openclaw:
    "somewhere your agent loads on startup (project rules, system prompt, or memory)",
  hermes: "~/.hermes/skills/cojournalist.md",
  other:
    "somewhere your agent loads on startup (project rules, system prompt, or memory)",
};

const CLI_INSTALL_LINE = `deno install -A -g -n cojo ${CLI_DENO_INSTALL_URL}`;

/**
 * Build a complete 1-click setup prompt that walks the agent (and user)
 * through connecting to coJournalist end-to-end. The agent:
 *
 *   1. Fetches skill.md so it understands the product
 *   2. Installs the cojo CLI (or configures MCP)
 *   3. Prompts the user for the API key and calls the right config command
 *   4. Verifies the connection
 *   5. Reports back what it can do and where it saved skill.md
 *
 * Paste this into any agent's first message and it self-configures.
 */
export function getSetupPrompt(
  slug: AgentSlug,
  path: InstallPath = "cli",
  target: AgentTargetContext = HOSTED_AGENT_TARGET,
): string {
  const location = SKILL_LOCATIONS[slug] ?? SKILL_LOCATIONS.other;
  const selfHostedNote = target.deploymentKind === "supabase"
    ? ` This is a self-hosted newsroom deployment; use only ${target.appUrl}, ${target.apiBaseUrl}, and ${target.mcpUrl}. Do not connect to cojournalist.ai.`
    : "";

  if (path === "mcp") {
    return [
      `Set me up with coJournalist.${selfHostedNote} Do this in order, narrating each step:`,
      ``,
      `1. Fetch ${target.skillUrl} and save it to ${location} so it auto-loads in future sessions. This is the product skill — it tells you how to drive coJournalist.`,
      `2. Configure the remote MCP server at ${target.mcpUrl}. If a config file edit is needed, show me the exact file path and diff before saving.`,
      `3. The MCP server uses OAuth — when the connector prompts me to sign in, I'll approve it in the browser. Do not ask me for a JWT or API key; the OAuth flow handles auth.`,
      `4. Verify the connection by listing my scouts. If the tool isn't available yet, tell me to reload the chat.`,
      `5. Summarise what coJournalist lets you do for me and suggest one concrete thing you'd use it for based on my current work.`,
    ].join("\n");
  }

  return [
    `Set me up with coJournalist via the cojo CLI.${selfHostedNote} Do this in order, narrating each step:`,
    ``,
    `1. Fetch ${target.skillUrl} and save it to ${location} so it auto-loads in future sessions. This is the product skill — it tells you how to drive coJournalist.`,
    `2. Install the cojo CLI by running: ${CLI_INSTALL_LINE}`,
    `   (Requires Deno 2.x. If Deno is missing, install it first from https://deno.com/.)`,
    `3. Tell me to generate an API key at ${target.apiKeyCreateUrl} → Agents → API → Create key (it's shown once). Do NOT ask me to paste the key into this chat — credentials in a transcript leak into logs and screenshots. Instead, have me run these commands in my own terminal so the key never enters the conversation:`,
    `     cojo config set api_url=${target.apiBaseUrl}`,
    ...(target.deploymentKind === "supabase"
      ? [`     cojo config set supabase_anon_key=${target.supabaseAnonKey || "<SUPABASE_ANON_KEY>"}`]
      : []),
    `     cojo config set api_key=cj_...   # I replace cj_... with the real key locally`,
    `4. After I confirm I've done that, verify by running: cojo --version && cojo scouts list — if it returns my scouts, we're connected. The CLI reads the key from ~/.cojournalist/config.json, so you never see it.`,
    `5. From now on, use the cojo CLI to create scouts, list findings, and verify units on my behalf. Don't ask me to open the web UI when you can do it via the CLI.`,
    `6. Summarise what coJournalist lets you do for me and suggest one concrete thing you'd use it for based on my current work.`,
  ].join("\n");
}

/** Backwards-compatible alias. */
export function getSkillPrompt(
  slug: AgentSlug,
  path: InstallPath = "cli",
  target: AgentTargetContext = HOSTED_AGENT_TARGET,
): string {
  return getSetupPrompt(slug, path, target);
}

/** @deprecated Use getSetupPrompt(agent, path) — kept for backwards compatibility. */
export const SKILL_PROMPT = getSetupPrompt("other", "cli");
